apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: my-cluster
spec:
  redis:
    replicas: 3
    affinity: &affinity
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
            - key: "app.stateful/component"
              operator: In
              values:
              - "redis-operator"
    tolerations: &tolerations
    - key: "app.stateful/component"
      operator: "Equal"
      value: "redis-operator"
      effect: NoSchedule
    topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: "topology.kubernetes.io/zone"
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          redisfailovers.databases.spotahome.com/name: my-cluster
          app.kubernetes.io/component: redis
    resources:
      requests:
        cpu: "1"
        memory: 4Gi
      limits:
        cpu: "2"
        memory: 4Gi
    exporter: 
      enabled: true
      image: oliver006/redis_exporter:v1.3.5-alpine
      args:
        - --web.telemetry-path
        - /metrics
      env:
        - name: REDIS_EXPORTER_LOG_FORMAT
          value: txt
  sentinel:
    replicas: 3
    affinity: *affinity
    tolerations: *tolerations
    topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: "topology.kubernetes.io/zone"
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          redisfailovers.databases.spotahome.com/name: my-cluster
          app.kubernetes.io/component: sentinel
    resources:
      requests:
        cpu: 100m
        memory: 500Mi
      limits:
        cpu: 500m
        memory: 500Mi

