apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis-enterprise
    redis.io/cluster: gke-rec-source
  name: gke-rec-source-headless
spec:
  clusterIP: None
  ports:
  - name: api
    port: 9443
    protocol: TCP
    targetPort: 9443
  - name: sentinel
    port: 8001
    protocol: TCP
    targetPort: 8001
  selector:
    app: redis-enterprise
    redis.io/cluster: gke-rec-source
    redis.io/role: node
  type: ClusterIP

