apiVersion: "app.redislabs.com/v1"
kind: "RedisEnterpriseCluster"
metadata:
  name: gke-rec-source
spec:
  nodes: 3
  redisEnterpriseNodeResources:
    limits:
      cpu: "2"
      memory: 4Gi
    requests:
      cpu: "1"
      memory: 4Gi
  podTolerations:
  - key: app.stateful/component
    operator: Equal     
    value: redis-operator
    effect: NoSchedule
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 1
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: "app.stateful/component"
            operator: In
            values:
            - "rec"
        topologyKey: "topology.kubernetes.io/zone"
  redisEnterpriseVolumeMounts:
  - name: nsswitch
    mountPath: /etc/nsswitch.conf
    subPath: nsswitch.conf
  volumes:
  - name: nsswitch
    configMap:
      name: nsswitch
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nsswitch
data:
  nsswitch.conf: |
    # /etc/nsswitch.conf
    #
    # Example configuration of GNU Name Service Switch functionality.
    # If you have the `glibc-doc-reference' and `info' packages installed, try:
    # `info libc "Name Service Switch"' for information about this file.
    
    passwd:         compat
    group:          compat
    shadow:         compat
    gshadow:        files
    
    hosts:          files dns mdns4_minimal [NOTFOUND=return]
    networks:       files
    
    protocols:      db files
    services:       db files
    ethers:         db files
    rpc:            db files
    
    netgroup:       nis

