apiVersion: app.redislabs.com/v1alpha1
kind: RedisEnterpriseRemoteCluster
metadata:
  name: source-cluster
spec:
  recName: gke-rec-source
  recNamespace: rec-ns
  apiFqdnUrl: gke-rec-source:9443
  dbFqdnSuffix: -headless.rec-ns.svc.redis-source.local
  secretName: redis-enterprise-source-cluster
