apiVersion: app.redislabs.com/v1alpha1
kind: RedisEnterpriseRemoteCluster
metadata:
  name: target-cluster
spec:
  recName: gke-rec-target
  recNamespace: rec-ns
  apiFqdnUrl: gke-rec-target.rec-ns.svc:9443
  dbFqdnSuffix: -headless.rec-ns.svc
  secretName: redis-enterprise-target-cluster
