apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
 - ../tgi-2b.yaml
patches:
  - path: patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: tgi-gemma-deployment

