apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
 - ../vllm-7b-it.yaml
patches:
  - path: patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: vllm-gemma-deployment

