# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# [START gke_databases_qdrant_04_client_pod]
apiVersion: v1
kind: Pod
metadata:
  name: qdrant-client
  annotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
spec:
  restartPolicy: Never
  containers:
  - name: qdrant-client
    image: python:3.11-slim-bookworm
    command: ["sleep", "3600"]
    resources:
      requests:
        memory: "3500Mi"
        cpu: "500m"
      limits:
        memory: "3500Mi"
        cpu: "1"
    env:
    - name: APIKEY
      valueFrom:
        secretKeyRef:
          name: qdrant-database-apikey
          key: api-key
    volumeMounts:
    - name: books-dataset
      mountPath: /usr/local/dataset
    - name: script-volume
      mountPath: /usr/local/script
  volumes:
  - name: books-dataset
    configMap:
      name: books-dataset
  - name: script-volume
    configMap:
      name: demo-app
 # [END gke_databases_qdrant_04_client_pod]
