apiVersion: v1
kind: PersistentVolume
metadata:
 name: model-fileserver
spec:
 capacity:
   storage: 30Gi
 accessModes:
 - ReadWriteMany
 nfs:
   path: /vol1
   server: <FILESTORE_IP>
 persistentVolumeReclaimPolicy: Retain
 storageClassName: standart
