apiVersion: v1
kind: Pod
metadata:
  name: kafkaclient
spec:
  containers:
  - name: main
    image: docker.io/bitnami/kafka:3.7.1-debian-12-r5 
    command: ["sleep", "720000"]
    resources:
      requests:
        memory: 1Gi
        cpu: "1"
      limits:
        memory: 1Gi
        cpu: "1"
    volumeMounts:
    - name: config
      mountPath: "/tmp/"
      readOnly: true
    - mountPath: /tmp/mm
      name: write-dir
  volumes:
  - name: config
    configMap:
      name: client-properties
  - name: write-dir
    emptyDir:
      sizeLimit: 100Mi
      medium: Memory
