sasl:
  client:
    users:
      - kafkauser
    passwords: "kafkapass"
extraConfig: |
  offsets.topic.replication.factor=1
  transaction.state.log.replication.factor=1
  default.replication.factor=1
controller:
  replicaCount: 1
  controllerOnly: false
  heapOpts: -Xmx4096m -Xms4096m
  resources:
    requests:
      memory: 8Gi
      cpu: "2"
    limits:
      memory: 8Gi
      cpu: "4"
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: "cloud.google.com/gke-nodepool"
            operator: In
            values:
            - "default-pool"
  persistence:
    enabled: true
    storageClass: "premium-rwo"
    accessModes:
      - ReadWriteOnce
    size: 150Gi
broker:
  replicaCount: 0
kraft:
  enabled: true
zookeeper:
  enabled: false

