# This file configures a GitHub Bot called "License Header Lint GCF": https://github.com/apps/license-header-lint-gcf
# The schema for this configutation file is documented at https://github.com/googleapis/repo-automation-bots/tree/main/packages/header-checker-lint#header-checker-lint.

allowedCopyrightHolders:
  - 'Google LLC'
allowedLicenses:
  - 'Apache-2.0'
ignoreFiles:
  - '**/requirements.txt'
# If you want to ignore checking the license year, uncomment the line below.
# ignoreLicenseYear: true # Useful when migrating in code licensed at previous years.
sourceFileExtensions:
  - 'cs'
  - 'Dockerfile'
  - 'go'
  - 'java'
  - 'js'
  - 'php'
  - 'py'
  - 'rb'
  - 'sh'
  - 'tf'
  - 'txt'
  - 'yaml'
  - 'yml'
