apiVersion: v1
kind: Pod
metadata:
  name: psql
spec:
  containers:
  - name: main
    image: postgres:16.0-alpine3.18
    command: ["sleep", "360000"]
    resources:
      requests:
        memory: 1Gi
        cpu: 500m
      limits:
        memory: 1Gi
        cpu: "1"
    env:
    - name: PGDATABASE
      value: postgres
    - name: PGUSER
      value: postgres
    - name: PGPASSWORD
      valueFrom:
        secretKeyRef:
          name: postgres-secret
          key: password

