apiVersion: apps/v1
kind: Deployment
metadata:
  name: tgi-gemma-deployment
spec:
  template:
    metadata:
      labels:
        ai.gke.io/model: llama-2-7b-awq
    spec:
      containers:
      - name: inference-server
        args:
        - --model-id=$(MODEL_ID)
        - --num-shard=1
        - --quantize=awq
        env:
        - name: MODEL_ID
          value: dganochenko/Llama-2-7B-AWQ

