---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bucket-access
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: download-script
data:
  download.sh: |-
    #!/usr/bin/bash -x
    apt-get update -y && \
      apt-get install -y --no-install-recommends \
      git git-lfs rsync
    git lfs install 
    cd /local-ssd
    echo "Saving dataset into Local SSD..."
    time git clone --depth=1 "$DATASET_REPO"
    echo "Saving dataset into Ram disk..."
    time rsync --info=progress2 -a /local-ssd/dataset/dataset/ /ram-disk/dataset/
    echo "Saving dataset into Bucket..."
    time gsutil -q -m cp -r /local-ssd/dataset/dataset/ gs://$BUCKET_NAME/dataset/
    echo "Dataset was successfully saved in all storages!"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: dataset-downloader
  labels:
    app: dataset-downloader
spec:
  ttlSecondsAfterFinished: 120
  template:
    metadata:
      labels:
        app: dataset-downloader
    spec:
      restartPolicy: OnFailure
      serviceAccountName: bucket-access
      containers:
      - name: gcloud
        image: gcr.io/google.com/cloudsdktool/google-cloud-cli:slim
        resources:
          requests:
            cpu: "2"
            memory: "12Gi"
          limits:
            cpu: "2"
            memory: "12Gi"
        command:
        - /scripts/download.sh
        env:
        - name: BUCKET_NAME
          value: <PROJECT_ID>-<CLUSTER_PREFIX>-model-train
        - name: DATASET_REPO
          value: "https://huggingface.co/datasets/dganochenko/dataset"
        - name: TIMEFORMAT
          value: "%0lR"
        volumeMounts:
        - name: local-ssd-storage
          mountPath: /local-ssd
        - name: ram-disk-storage
          mountPath: /ram-disk
        - name: scripts-volume
          mountPath: "/scripts/"
          readOnly: true
      volumes:
      - name: scripts-volume
        configMap:
          defaultMode: 0700
          name: download-script
      - name: local-ssd-storage
        persistentVolumeClaim:
          claimName: local-ssd-claim
      - name: ram-disk-storage
        persistentVolumeClaim:
          claimName: ram-disk-claim
      - name: gcs-fuse-storage
        persistentVolumeClaim:    
          claimName: gcs-fuse-claim
      tolerations:
      - key: "nvidia.com/gpu"
        operator: "Equal"
        value: "present"
        effect: NoSchedule
      - key: "app.stateful/component"
        operator: "Equal"
        value: "model-train"
        effect: NoSchedule
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-l4
