apiVersion: v1
kind: Pod
metadata:
  name: client
  annotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
spec:
  serviceAccountName: vertexai
  restartPolicy: Never
  containers:
  - name: client
    image: python:3.11
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
    resources:
      requests:
        memory: "1024Mi"
        cpu: "1"
      limits:
        memory: "1024Mi"
        cpu: "1"
    env:
    - name: QDRANT_APIKEY 
      valueFrom:
        secretKeyRef:
          name: qdrant-database-apikey          
          key: api-key
    - name: QDRANT_ENDPOINT
      value: "http://qdrant-database.qdrant:6334"
    volumeMounts:
    - name: dataset
      mountPath: /usr/local/dataset
  volumes:
  - name: dataset
    configMap:
      name: dataset

