apiVersion: v1
kind: PersistentVolume
metadata:
  name: backup
  labels:
    topology.kubernetes.io/region: us-central1
    topology.kubernetes.io/zone: us-central1-c
  finalizers:
    - kubernetes.io/pv-protection
spec:
  storageClassName: balanced-storage
  capacity:
    storage: 150G
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  gcePersistentDisk:
    pdName: pvc-54cb6bc2-0139-4883-bd5e-2cf09a623eb5
    fsType: ext4

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  name: hyperdisk-recovery
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 150G
  volumeName: backup
  storageClassName: balanced-storage