sasl:
  client:
    users:
      - benchmark
    passwords: "benchmark"
controller:
  replicaCount: 1
  controllerOnly: false
  heapOpts: -Xmx4096m -Xms4096m
  resources:
    requests:
      memory: 8Gi
      cpu: "2"
    limits:
      memory: 8Gi
      cpu: "4"
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: "app.stateful/component"
            operator: In
            values:
            - "data-cache"
  tolerations:
  - key: "app.stateful/component"
    operator: "Equal"
    value: "data-cache"
    effect: NoSchedule
  persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 150Gi
broker:
  replicaCount: 0
kraft:
  enabled: true
zookeeper:
  enabled: false

