# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-b
  template:
    metadata:
      labels:
        app: pod-b
    spec:
      containers:
      - name: ubuntu
        command: [ "/bin/sh", "-c" ]
        args: [ "cd /data/; md5sum */* */*/* 2>/dev/null; sleep 3600s" ]
        image: ubuntu:22.04
        resources:
          limits:
            cpu: '2'
            memory: 4Gi
          requests:
            cpu: '1'
            memory: 4Gi
        volumeMounts:
        - name: gke-gcsfuse-cache
          mountPath: /data
          subPath: .volumes/gcs-fuse-csi-ephemeral/gcsfuse-file-cache
          readOnly: true
      nodeSelector:
        cloud.google.com/gke-local-nvme-ssd: "true"
        node.kubernetes.io/instance-type: "c4-standard-4-lssd"
      volumes:
      - name: gke-gcsfuse-cache
        persistentVolumeClaim:
          claimName: local-raid-pvc       


