apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-a
  template:
    metadata:
      labels:
        app: pod-a
      annotations:
        gke-gcsfuse/volumes: "true"
    spec:
      serviceAccountName: bucket-sa
      containers:
      - name: ubuntu
        command: [ "/bin/sh", "-c" ]
        args: [ "cd /data/; md5sum * */* 2>/dev/null; sleep 3600s" ]
        image: ubuntu:22.04
        resources:
          limits:
            cpu: '2'
            memory: 4Gi
          requests:
            cpu: '1'
            memory: 4Gi
        volumeMounts:
        - name: gcs-fuse-csi-ephemeral
          mountPath: /data
          readOnly: true
      nodeSelector:
        cloud.google.com/gke-local-nvme-ssd: "true"
        node.kubernetes.io/instance-type: "c4-standard-4-lssd"
      volumes:
      - name: gcs-fuse-csi-ephemeral
        csi:
          driver: gcsfuse.csi.storage.gke.io
          readOnly: true
          volumeAttributes:
            bucketName: "your-bucket-name"
            mountOptions: "implicit-dirs,file-cache:enable-parallel-downloads:true,file-cache:cache-file-for-range-read:false,file-cache:download-chunk-size-mb:32,file-cache:max-size-mb:-1,metadata-cache:stat-cache-max-size-mb:32,metadata-cache:ttl-secs:3600,metadata-cache:type-cache-max-size-mb:4" 
      - name: gke-gcsfuse-cache
        persistentVolumeClaim:
          claimName: local-raid-pvc       


