apiVersion: v1
kind: Pod
metadata:
  name: redis-client-tls
spec:
  containers:
  - name: redis-client
    image: redis:latest
    command: ["sleep", "3600"]
    volumeMounts:
      - name: ca-pair
        readOnly: true
        mountPath: "/cert"
  volumes:
    - name: ca-pair
      secret:
        secretName: ca-pair

