apiVersion: v1
kind: Pod
metadata:
  name: redis-client-mtls
spec:
  containers:
  - name: redis-client
    image: redis:latest
    command: ["sleep", "3600"]
    volumeMounts:
      - name: client-certificate
        readOnly: true
        mountPath: "/cert"
  volumes:
    - name: client-certificate
      secret:
        secretName: client-certificate

