# model-storage-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-storage
  namespace: axolotl-training
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi