---
apiVersion: v1
kind: Service
metadata:
  labels: &labels
    app: jupyter-notebook
  name: notebook
spec:
  ports:
  - port: 8888
  selector: *labels
  #type: LoadBalancer
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notebook
  labels: &labels
    app: jupyter-notebook
spec:
  selector:
    matchLabels: *labels
  template:
    metadata:
      annotations:
        gke-gcsfuse/volumes: "true"
      labels: *labels
    spec:
      serviceAccountName: bucket-access
      containers:
      - name: jupyter
        image: quay.io/jupyter/pytorch-notebook:cuda12-pytorch-2.4.0
        resources:
          requests:
            cpu: "2"
            memory: "16Gi"
            nvidia.com/gpu: 1
          limits:
            cpu: "2"
            memory: "16Gi"
            nvidia.com/gpu: 1
        ports:
        - containerPort: 8888
        volumeMounts:
          - name: dshm
            mountPath: /dev/shm
          - name: notebook
            mountPath: /tf
          - name: local-ssd-storage
            mountPath: /local-ssd
          - name: ram-disk-storage
            mountPath: /ram-disk
          - name: gcs-fuse-storage
            mountPath: /bucket
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      - name: notebook
        configMap:
          name: notebook
      - name: local-ssd-storage
        persistentVolumeClaim:
          claimName: local-ssd-claim
      - name: ram-disk-storage
        persistentVolumeClaim:
          claimName: ram-disk-claim
      - name: gcs-fuse-storage
        persistentVolumeClaim:    
          claimName: gcs-fuse-claim
      tolerations:
      - key: "nvidia.com/gpu"
        operator: "Equal"
        value: "present"
        effect: NoSchedule
      - key: "app.stateful/component"
        operator: "Equal"
        value: "model-train"
        effect: NoSchedule
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-l4
