---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bucket-access
---
apiVersion: v1
kind: Service
metadata:
  labels: &labels
    app: jupyter-notebook
  name: notebook
spec:
  ports:
  - port: 8888
  selector: *labels
  #type: LoadBalancer
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notebook
  labels: &labels
    app: jupyter-notebook
spec:
  selector:
    matchLabels: *labels
  template:
    metadata:
      annotations:
        gke-gcsfuse/volumes: "true"
      labels: *labels
    spec:
      serviceAccountName: bucket-access
      containers:
      - name: jupyter
        image: tensorflow/tensorflow:2.15.0-jupyter
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        resources:
          requests:
            memory: "1000Mi"
            cpu: "1"
          limits:
            memory: "1000Mi"
            cpu: "1"
#          requests:
#            cpu: "2"
#            memory: "7Gi"
#            ephemeral-storage: "5Gi"
#            nvidia.com/gpu: 1
#          limits:
#            cpu: "2"
#            memory: "7Gi"
#            ephemeral-storage: "5Gi"
#            nvidia.com/gpu: 1
        ports:
        - containerPort: 8888
        volumeMounts:
          - name: dshm
            mountPath: /dev/shm
          - name: local-ssd-storage
            mountPath: /local-ssd
          - name: ram-disk-storage
            mountPath: /ram-disk
          - name: gcs-fuse-storage
            mountPath: /bucket
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      - name: local-ssd-storage
        persistentVolumeClaim:
          claimName: local-ssd-claim
      - name: ram-disk-storage
        persistentVolumeClaim:
          claimName: ram-disk-claim
      - name: gcs-fuse-storage
        persistentVolumeClaim:
          claimName: gcs-fuse-claim
      tolerations:
      - key: "nvidia.com/gpu"
        operator: "Equal"
        value: "present"
        effect: NoSchedule
#      nodeSelector:
#        cloud.google.com/gke-accelerator: nvidia-l4
