---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gcs-fuse-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 16Gi
  storageClassName: example-storage-class
  mountOptions:
    - implicit-dirs
  csi:
    driver: gcsfuse.csi.storage.gke.io
    volumeHandle: <PROJECT_ID>-<CLUSTER_PREFIX>-model-train
    volumeAttributes:
      fileCacheCapacity: 5Gi
      fileCacheForRangeRead: "true"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gcs-fuse-claim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 16Gi
  volumeName: gcs-fuse-pv
  storageClassName: example-storage-class
