# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file and other cloudbuild.yaml files are used to ensure that
# our public Docker images such as us-docker.pkg.dev/google-samples/containers/gke/whereami:v1.2.2
# are rebuilt and updated upon changes to the repository.

steps:
# Temporarily removed for faster testing
- name: ubuntu
  script: |
    apt update
    apt install curl -y
    curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
    cd quickstarts/whereami/helm-chart
    helm package . # This creates a file similar to whereami-X.Y.Z.tgz
    helm push whereami-1.2.23.tgz oci://us-docker.pkg.dev/google-samples/charts
    
    # Push Helm chart which allows users to refer to the chart by just the major tag (and pull the latest patch).
    # Unfortunately, we cannot reuse the whereami-X.Y.Z.tgz file/package created above.
    # We need to update the "version" and "appVersion" values in Chart.yaml and repackage.
    sed -i "s/version: .*/version: 1/" Chart.yaml
    sed -i "s/appVersion: .*/appVersion: \"1\"/" Chart.yaml
    helm package . # This creates a file similar to whereami-X.tgz
    helm push whereami-1.tgz oci://us-docker.pkg.dev/google-samples/charts/whereami

images:
  - 'gcr.io/google-samples/whereami:v1'
  - 'gcr.io/google-samples/whereami:v1.2.23'
  - 'gcr.io/google-samples/whereami:sample-public-image-v1.2.23-${SHORT_SHA}'
  - 'us-docker.pkg.dev/google-samples/containers/gke/whereami:v1'
  - 'us-docker.pkg.dev/google-samples/containers/gke/whereami:v1.2.23'
  - 'us-docker.pkg.dev/google-samples/containers/gke/whereami:sample-public-image-v1.2.23-${SHORT_SHA}'
  - 'europe-docker.pkg.dev/google-samples/containers/gke/whereami:v1'
  - 'europe-docker.pkg.dev/google-samples/containers/gke/whereami:v1.2.23'
  - 'europe-docker.pkg.dev/google-samples/containers/gke/whereami:sample-public-image-v1.2.23-${SHORT_SHA}'
