# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# [START gke_databases_milvus_02_ilb]
apiVersion: v1
kind: Service
metadata:
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
  labels:
    app.kubernetes.io/name: milvus
  name: milvus-ilb
spec:
  ports:
  - name: milvus
    port: 19530
    protocol: TCP
    targetPort: milvus
  selector:
    app.kubernetes.io/name: milvus
    component: proxy
  type: LoadBalancer
# [END gke_databases_milvus_02_ilb]

