---
apiVersion: v1
kind: Pod
metadata:
  name: kafkacat-mtls
spec:
  containers:
  - name: kafkacat
    image: confluentinc/cp-kcat:7.4.0
    command: ["sh", "-c", "exec tail -f /dev/null"]
    volumeMounts:
    - name: my-user
      mountPath: "/my-user"
      readOnly: true
    - name: config-volume
      mountPath: /home/appuser/.config
  volumes:
  - name: my-user
    secret:
      secretName: my-user-credentials
  - name: config-volume
    configMap:
      name: kcat-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kcat-config
data:
  kcat.conf: enable.ssl.certificate.verification=false
