apiVersion: v1
kind: Pod
metadata:
  name: sysbench
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: "app.stateful/component"
            operator: NotIn
            values:
            - "data-cache"
  tolerations:
  - key: "app.stateful/component"
    operator: "Equal"
    value: "data-cache"
    effect: NoSchedule
  containers:
  - name: main
    image: perconalab/sysbench
    command: ["sleep", "720000"]
    resources:
      requests:
        memory: 2Gi
        cpu: "1"
      limits:
        memory: 2Gi
        cpu: "2"
    env:
    - name: LUA_PATH
      value: /sysbench/sysbench-tpcc/?.lua
    - name: MYSQL_ROOT_PASSWORD
      value: benchmark
    resources:
      requests:
        cpu: 1000m
        memory: 1Gi
      limits:
        cpu: 1000m
        memory: 1Gi