# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# [START gke_databases_data_cache_mysql_cluster]
image:
  registry: docker.io
  repository: bitnami/mysql
  tag: 8.4.3-debian-12-r0 
  pullPolicy: IfNotPresent

architecture: standalone
auth:
  rootPassword: "benchmark"
  createDatabase: true
  database: "my_database"
primary:
  resources:
    requests:
      cpu: "2"
      memory: 8Gi
    limits:
      cpu: "4"
      memory: 8Gi
  affinity: 
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: "app.stateful/component"
            operator: In
            values:
            - "data-cache"
  tolerations:
  - key: "app.stateful/component"
    operator: "Equal"
    value: "data-cache"
    effect: NoSchedule
  extraFlags: "--max_connections=400"
  persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 150Gi
# [END gke_databases_data_cache_mysql_cluster]

