apiVersion: apps/v1
kind: Deployment
metadata:
  name: tgi-gemma-deployment
spec:
  template:
    metadata:
      labels:
        ai.gke.io/model: gemma-2b-it-gptq
    spec:
      containers:
      - name: inference-server
        args:
        - --model-id=$(MODEL_ID)
        - --num-shard=1
        - --quantize=gptq
        env:
        - name: MODEL_ID
          value: TheBloke/Llama-2-7B-Chat-GPTQ


