apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-gemma-deployment
spec:
  template:
    metadata:
      labels:
        ai.gke.io/model: gemma-7b-gptq
    spec:
      containers:
      - name: inference-server
        args:
        - --model=$(MODEL_ID)
        - --tensor-parallel-size=2
        - --quantization=gptq
        env:
        - name: MODEL_ID
          value: TechxGenus/gemma-7b-GPTQ

