apiVersion: v1
kind: PersistentVolume
metadata:
  name: fileserver
spec:
  capacity:
    storage: 1T
  # Setting the accessModes to ReadWriteMany is essential for 
  # allowing > 2 writers to be writing to the same storage
  accessModes:
  - ReadWriteMany
  nfs:
    path: /statefulpath
    # Replace {IP_ADDRESS} with the IP address 
    # from the newly created Filestore instance
    server: <IP_ADDRESS>

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fileserver
spec:
  # Specify "" as the storageClassName so it matches the PersistentVolume's StorageClass.
  # A nil storageClassName value uses the default StorageClass. For details, see
  # https://kubernetes.io/docs/concepts/storage/persistent-volumes/#class-1
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  volumeName: fileserver
  resources:
    requests:
      storage: 1T