apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-gemma-deployment
spec:
  template:
    metadata:
      labels:
        ai.gke.io/model: gemma-2b-it-awq
    spec:
      containers:
      - name: inference-server
        args:
        - --model=$(MODEL_ID)
        - --tensor-parallel-size=1
        - --quantization=awq
        env:
        - name: MODEL_ID
          value: TechxGenus/gemma-2b-it-AWQ

