apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: llm-prometheus
  labels:
    app.kubernetes.io/name: llm-prometheus
spec:
  endpoints:
  - port: web
    scheme: http
    interval: 30s
    path: /metrics
  selector:
    matchLabels:
      app: gemma-server