global:
  imageRegistry: ""
  imagePullSecrets: []
  defaultStorageClass: ""
  storageClass: ""
  compatibility:
    openshift:
      adaptSecurityContext: auto

image:
  registry: docker.io
  repository: bitnami/mysql
  tag: 8.4.3-debian-12-r4
  pullPolicy: IfNotPresent
  pullSecrets: []
  debug: false
architecture: replication

auth:
  rootPassword: "migration"
  createDatabase: true
  database: "my_database"
  username: "app"
  password: "migration"
  replicationUser: replicator
  replicationPassword: "migration"

primary:
  resources:
    requests:
      cpu: "2"
      memory: 8Gi
    limits:
      cpu: "4"
      memory: 8Gi

  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: "cloud.google.com/gke-nodepool"
            operator: In
            values:
            - "default-pool"
  extraFlags: "--max_connections=400"
  persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 150Gi
  service:
    type: NodePort
    ports:
      mysql: 3306
    nodePorts:
      mysql: "31006"

secondary:
  replicaCount: 2
  resources:
    requests:
      cpu: "2"
      memory: 8Gi
    limits:
      cpu: "4"
      memory: 8Gi
  affinity: 
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: "cloud.google.com/gke-nodepool"
            operator: In
            values:
            - "pool-hyperdisk"
  persistence:
    enabled: true
    accessModes:
    - ReadWriteOnce
    size: 150Gi  
  service:
    type: NodePort
    ports:
      mysql: 3306
    nodePorts:
      mysql: "31005"    