apiVersion: v1
kind: Pod
metadata:
  name: pg-client
  annotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: "true"

spec:
  restartPolicy: Never
  containers:
  - name: pg-client
    image: postgres:15-alpine
    command: ["sleep", "3600"]
    env:
    - name: CLIENTPASSWORD
      valueFrom:
        secretKeyRef:
          name: gke-pg-cluster-app
          key: password
    - name: CLIENTUSERNAME
      valueFrom:
        secretKeyRef:
          name: gke-pg-cluster-app
          key: username
    - name: OWNERPASSWORD
      valueFrom:
        secretKeyRef:
          name: gke-pg-cluster-superuser
          key: password
    - name: OWNERUSERNAME
      valueFrom:
        secretKeyRef:
          name: gke-pg-cluster-superuser
          key: username