apiVersion: v1
kind: Pod
metadata:
  name: chclient
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: "app.stateful/component"
            operator: NotIn
            values:
            - "data-cache"
  tolerations:
  - key: "app.stateful/component"
    operator: "Equal"
    value: "data-cache"
    effect: NoSchedule
  containers:
  - name: main
    image: bitnami/clickhouse:24
    command: ["sleep", "360000"]
    resources:
      requests:
        memory: 2Gi
        cpu: "1"
      limits:
        memory: 2Gi
        cpu: "2"
    volumeMounts:
    - name: configmap
      mountPath: /queries
  volumes:
    - name: configmap
      configMap:
        name: ch-benchmark
