apiVersion: v1
kind: Service
metadata:
  name: backend
  annotations:
    networking.gke.io/load-balancer-type: Internal
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: backend
