---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    user nginx;
    worker_processes  1;
    error_log  /var/log/nginx/error.log warn;
    events {
      worker_connections  10240;
    }
    http {
      server {
          listen       80;
          location / {
            proxy_pass https://gke-rec-prom:8070;
            proxy_http_version 1.1;
            proxy_ssl_verify off;
            proxy_set_header Host $http_host;
            proxy_set_header X-Forwarded-For $remote_addr;
          }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-proxy
spec:
  selector:
    matchLabels:
      redis.io/cluster: gke-rec
      component: metrics-proxy
  replicas: 1
  template:
    metadata:
      labels:
        redis.io/cluster: gke-rec
        component: metrics-proxy
    spec:
      containers:
      - name: nginx
        image: nginx:1.25
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf
          items:
            - key: nginx.conf
              path: nginx.conf
