apiVersion: v1
kind: Pod
metadata:
  name: client
  annotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
spec:
  restartPolicy: Never
  containers:
  - name: client
    image: python:3.11
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
    env:
    - name: OWNERPASSWORD
      valueFrom:
        secretKeyRef:
          name: mydatabaseowner.my-cluster.credentials.postgresql.acid.zalan.do
          key: password
    - name: OWNERUSERNAME
      valueFrom:
        secretKeyRef:
          name: mydatabaseowner.my-cluster.credentials.postgresql.acid.zalan.do
          key: username
    - name: POSTGRES_URL
      value: my-cluster.postgres
    - name: DATABASE_NAME
      value: mydatabase
    - name: LLM_ENDPOINT
      value: http://llm-service.llm:8000/
