steps:
  # Build step 1 where we clone the model using a git image
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update && 
        apt-get install -y git-lfs &&
        git lfs install &&
        git clone https://$$HF_USERNAME:$$HF_TOKEN@huggingface.co/google/${_MODEL_NAME} ./${_MODEL_NAME} &&
    secretEnv: ['HF_USERNAME', 'HF_TOKEN']

  # Build step 2 where we build our Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'MODEL_NAME=${_MODEL_NAME}'
      - '-t'
      - 'us-central1-docker.pkg.dev/$_PROJECT_ID/$_REPOSITORY_NAME/$_IMAGE_NAME'
      - '.'

options:
  machineType: 'UNSPECIFIED' # please replace with the required machine type
  diskSizeGb: 500            # please replace with the proper disk size in Gidabytes

images: 
  - '$_REGION-docker.pkg.dev/$_PROJECT_ID/$_REPOSITORY_NAME/$_IMAGE_NAME'

availableSecrets:
  secretManager:
  - versionName: projects/$_PROJECT_ID/secrets/hf-username/versions/latest
    env: 'HF_USERNAME'
  - versionName: projects/$_PROJECT_ID/secrets/hf-token/versions/latest
    env: 'HF_TOKEN'
