apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ${METRICS_READER_CLUSTER_ROLE_NAME:-inference-gateway-metrics-reader}
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${METRICS_READER_SA_NAME:-inference-gateway-sa-metrics-reader}
  namespace: ${NAMESPACE:-default}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ${METRICS_READER_ROLE_BINDING_NAME:-inference-gateway-sa-metrics-reader-role-binding}
  namespace: ${NAMESPACE:-default}
subjects:
- kind: ServiceAccount
  name: ${METRICS_READER_SA_NAME:-inference-gateway-sa-metrics-reader}
  namespace: ${NAMESPACE:-default}
roleRef:
  kind: ClusterRole
  name: ${METRICS_READER_CLUSTER_ROLE_NAME:-inference-gateway-metrics-reader}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  name: ${METRICS_READER_SECRET_NAME:-inference-gateway-sa-metrics-reader-secret}
  namespace: ${NAMESPACE:-default}
  annotations:
    kubernetes.io/service-account.name: ${METRICS_READER_SA_NAME:-inference-gateway-sa-metrics-reader}
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ${METRICS_READER_SECRET_READ_CLUSTER_ROLE_NAME:-inference-gateway-sa-metrics-reader-secret-read}
rules:
- resources:
  - secrets
  apiGroups: [""]
  verbs: ["get", "list", "watch"]
  resourceNames: ["${METRICS_READER_SECRET_NAME:-inference-gateway-sa-metrics-reader-secret}"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ${METRICS_COLLECTOR_ROLE_BINDING_NAME:-gmp-system:collector:inference-gateway-sa-metrics-reader-secret-read}
  namespace: ${NAMESPACE:-default}
roleRef:
  name: ${METRICS_READER_SECRET_READ_CLUSTER_ROLE_NAME:-inference-gateway-sa-metrics-reader-secret-read}
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
- name: ${METRICS_COLLECTOR_SA_NAME:-collector}
  namespace: ${METRICS_COLLECTOR_NAMESPACE:-gmp-system}
  kind: ServiceAccount