apiVersion: v1
kind: Service
metadata:
  name: headless-svc-l4
spec:
  clusterIP: None # clusterIP must be None to create a headless service
  selector:
    job-name: finetune-gemma-l4 # must match Job name
---
apiVersion: batch/v1
kind: Job
metadata:
  name: finetune-gemma-l4
  labels:
    kueue.x-k8s.io/queue-name: lq
spec:
  backoffLimit: 4
  completions: 2
  parallelism: 2
  completionMode: Indexed
  template:
    metadata:
      labels:
        app: finetune-job
      annotations:
        gke-gcsfuse/volumes: "true"
        gke-gcsfuse/memory-limit: "35Gi"
        # cluster-autoscaler.kubernetes.io/consume-provisioning-request: l4-job
        # cluster-autoscaler.kubernetes.io/provisioning-class-name: "queued-provisioning.gke.io"
    spec:
      priorityClassName: low-priority-preempting
      containers:
      - name: gpu-job
        imagePullPolicy: Always 
        image: us-central1-docker.pkg.dev/or2-msq-go2-gkes-t1iylu/fine-tuning/fine-tuning:1.1.2
        ports:
        - containerPort: 29500
        securityContext:
          privileged: true
        resources:
          requests:
            nvidia.com/gpu: "2"
          limits:
            nvidia.com/gpu: "2"
        command:
          - bash
          - -c
          - |
            accelerate launch \
            --config_file fsdp_config.yaml \
            --debug \
            --main_process_ip finetune-gemma-l4-0.headless-svc-l4 \
            --main_process_port 29500 \
            --machine_rank ${JOB_COMPLETION_INDEX} \
            --num_processes 4 \
            --num_machines 2 \
            fine_tune.py
        env:
        - name: "EXPERIMENT"
          value: "finetune-experiment"
        - name: "MLFLOW_ENABLE"
          value: "false"
        # - name: "MLFLOW_TRACKING_URI"
        #   value: "http://mlflow-tracking-svc:5000"
        - name: "MLFLOW_ENABLE_SYSTEM_METRICS_LOGGING"
          value: "false"
        - name: "TRAINING_DATASET_BUCKET"
          value: "data-bucket-or2-msq-go2-gkes-t1iylu"
        - name: "TRAINING_DATASET_PATH"
          value: "training"
        - name: MODEL_NAME
          value: "google/gemma-2-9b-it"
        - name: NEW_MODEL
          value: "gemma-ft"
        - name: MODEL_PATH
          value: "/model-data/model-gemma2/experiment"
        - name: EPOCHS
          value: "1"
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-secret
              key: hf_api_token
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
        - name: gcs-fuse-csi-ephemeral
          mountPath: /model-data
          readOnly: false
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-l4
      restartPolicy: OnFailure
      serviceAccountName: default
      subdomain: headless-svc-l4
      terminationGracePeriodSeconds: 600
      tolerations:
      - key: "ondemand"
        operator: "Exists"
        effect: NoSchedule
      - key: "nvidia.com/gpu"
        operator: "Exists"
        effect: NoSchedule
      # - key: "ondemand"
      #   value: "true"
      #   operator: "Equal"
      #   effect: "NoSchedule"
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      - name: gcs-fuse-csi-ephemeral
        csi:
          driver: gcsfuse.csi.storage.gke.io
          volumeAttributes:
            bucketName: model-bucket-or2-msq-go2-gkes-t1iylu
            mountOptions: "implicit-dirs"
            gcsfuseLoggingSeverity: warning
