name: cost-optimization-hpa-config-recommender-ci

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/cost-optimization-hpa-config-recommender-ci.yml'
      - 'cost-optimization/hpa-config-recommender/**'
  pull_request:
    paths:
      - '.github/workflows/cost-optimization-hpa-config-recommender-ci.yml'
      - 'cost-optimization/hpa-config-recommender/**'

jobs:
  build_and_test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Validate terraform
        run: |
          cd cost-optimization/hpa-config-recommender/deploy
          terraform init
          terraform validate

      - name: Build and test buildtest Docker image
        run: |
          cd cost-optimization/hpa-config-recommender
          docker build \
            --build-arg PROJECT_SUBDIRECTORY=. \
            -t buildtest .

          docker run buildtest \
            python3 -m venv .venv && \
            . .venv/bin/activate && \
            python3 -m pip install --upgrade pip && \
            python3 -m pip install --no-cache-dir --use-pep517 -e . && \
            python3 -m unittest discover -s . -p 'test_*.py'

      - name: Check buildtest exit code
        run: |
          if [ $? -ne 0 ]; then
            echo "buildtest container failed. Exiting with error."
            exit 1
          fi
