name: cost-optimization-hpa-config-recommender-ci

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/cost-optimization-hpa-config-recommender-ci.yml'
      - 'cost-optimization/hpa-config-recommender/**'
  pull_request:
    paths:
      - '.github/workflows/cost-optimization-hpa-config-recommender-ci.yml'
      - 'cost-optimization/hpa-config-recommender/**'

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate terraform
        run: |
          cd cost-optimization/hpa-config-recommender/deploy
          terraform init
          terraform validate

      - name: Set up Python 3.12.5
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.5

      - name: Build and run tests
        run: |
          cd ../
          python3 -m venv.venv
          source.venv/bin/activate
          python3 -m pip install --upgrade pip
          python3 -m pip install --no-cache-dir --use-pep517 -e.[dev]
          pytest  # Run pytest
