name: databases-postgresql-cnpg.yml
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/databases-postgresql-cnpg.yml'
      - 'databases/postgresql-cloudnativepg/**'
  pull_request:
    paths:
      - '.github/workflows/databases-postgresql-cnpg.yml'
      - 'databases/postgresql-cloudnativepg/**'
jobs:
  job:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Validate GKE Standard TF for CloudNativePG
        run: |
          cd databases/postgresql-cloudnativepg/terraform/gke-standard 
          terraform init
          terraform validate
      - name: Validate GKE Autopilot TF for CloudNativePG
        run: |
          cd databases/postgresql-cloudnativepg/terraform/gke-autopilot
          terraform init
          terraform validate