name: databases-ci.yml
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/databases-ci.yml'
      - 'databases'
  pull_request:
    paths:
      - '.github/workflows/databases-ci.yml'
      - 'databases'
jobs:
  job:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: build hello-app-cloud-spanner container
        run: |
          cd databases/hello-app-cloud-spanner
          docker build --tag hello-app-cloud-spanner .
      - name: Validate GKE Autopilot TF for Spotahome
        run: |
          cd databases/redis-spotahome/terraform/gke-autopilot
          terraform init
          terraform validate
      - name: Validate GKE Standard TF for Spotahome
        run: |
          cd databases/redis-spotahome/terraform/gke-standard
      - name: Validate GKE Autopilot TF for Redis replication
        run: |
          cd databases/redis/terraform/gke-replication
          terraform init
          terraform validate

