name: distributed-tracing-ci
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/distributed-tracing-ci.yml'
      - 'monitoring/distributed-tracing/**'
  pull_request:
    paths:
      - '.github/workflows/distributed-tracing-ci.yml'
      - 'monitoring/distributed-tracing/**'
jobs:
  job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: build distributed-tracing container
        run: |
          cd monitoring/distributed-tracing
          docker build .
