name: gke-vpa-recommendations-ci
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/gke-vpa-recommendations-ci.yml'
      - 'gke-vpa-recommendations/**'
  pull_request:
    paths:
      - '.github/workflows/gke-vpa-recommendations-ci.yml'
      - 'gke-vpa-recommendations/**'
jobs:
  job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Validate terraform
        run: |
          cd gke-vpa-recommendations/metrics-exporter/terraform
          terraform init
          terraform validate