name: monitoring-ci
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/monitoring-ci.yml'
      - 'monitoring/**'
  pull_request:
    paths:
      - '.github/workflows/monitoring-ci.yml'
      - 'monitoring/**'
jobs:
  distributed-tracing:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: build distributed-tracing container
        run: |
          cd monitoring/distributed-tracing
          docker build .
