# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sglang
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: sglang
  template:
    metadata:
      labels:
        app: sglang
    spec:
      restartPolicy: Always
      containers:
      - name: sglang
        image: dganochenko/sglang:v0.5.5
        imagePullPolicy: Always
        env:
        - name: AWS_ACCESS_KEY_ID
          value: ""
        - name: AWS_SECRET_ACCESS_KEY
          value: ""
        ports:
        - containerPort: 30000
        command: ["python3", "-m", "sglang.launch_server"]
        args: ["--model-path", "gs://epam-team-llama-3-70b/Llama-3.3-70B-Instruct", "--served-model-name", "unsloth/Llama-3.3-70B-Instruct", "--load-format", "remote", "--host", "0.0.0.0", "--port", "30000", "--tp-size", "8", "--context-length",  "8192"]
        resources:
          limits:
            nvidia.com/gpu: '8'
          requests:
            nvidia.com/gpu: '8'
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
      tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Equal
        value: present
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-l4
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory


