# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vllm
  template:
    metadata:
      labels:
        app: vllm
    spec:
      #serviceAccountName: bucket-sa
      containers:
        #- command: [ "/bin/sh", "-c", "sleep 36000" ]
      - command: [ "/bin/sh", "-c" ]
        args: [ "vllm serve s3://test-bucket-666666/Llama-3.3-70B-Instruct --load-format runai_streamer --max-model-len 8192 --max-num-seqs 2 --gpu-memory-utilization=0.95 --served-model-name unsloth/Llama-3.3-70B-Instruct --tensor-parallel-size=8" ]
        image: vllm/vllm-openai:nightly
        env:
        - name: AWS_ACCESS_KEY_ID
          value: ""
        - name: AWS_SECRET_ACCESS_KEY
          value: ""
        name: inference-server
        resources:
          limits:
            nvidia.com/gpu: '8'
          requests:
            nvidia.com/gpu: '8'
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
      tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Equal
        value: present
      nodeSelector:
        nodegroup-type: p5-gpu-workers
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
---
apiVersion: v1
kind: Service
metadata:
  name: vllm-endpoint
spec:
  selector:
    app: vllm
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
